[connections.snowflake]
account = "LAYJUAU.YO72939"
user = "CSSANDOR"
password = "Johanna2024"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
